//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathMedical.AudiologyTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathMedical.AudiologyTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string AudiologyTestInformation_Examiner_Unknown_Screener {
            get {
                return ResourceManager.GetString("AudiologyTestInformation_Examiner_Unknown_Screener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted by user.
        /// </summary>
        public static string CalibrationAbort {
            get {
                return ResourceManager.GetString("CalibrationAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CalibrationError {
            get {
                return ResourceManager.GetString("CalibrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaky probe fit.
        /// </summary>
        public static string CalibrationLeaky {
            get {
                return ResourceManager.GetString("CalibrationLeaky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration timeout.
        /// </summary>
        public static string CalibrationTimeout {
            get {
                return ResourceManager.GetString("CalibrationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ear_Left {
            get {
                object obj = ResourceManager.GetObject("Ear_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ear_Right {
            get {
                object obj = ResourceManager.GetObject("Ear_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ElectrodeLoose {
            get {
                return ResourceManager.GetString("ElectrodeLoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GN_TestIncomplete {
            get {
                object obj = ResourceManager.GetObject("GN_TestIncomplete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GN_TestPass {
            get {
                object obj = ResourceManager.GetObject("GN_TestPass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GN_TestRefer {
            get {
                object obj = ResourceManager.GetObject("GN_TestRefer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap impdance_red {
            get {
                object obj = ResourceManager.GetObject("impdance_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap impdance_white {
            get {
                object obj = ResourceManager.GetObject("impdance_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Test.
        /// </summary>
        public static string IncompleteTest {
            get {
                return ResourceManager.GetString("IncompleteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MeasurementAbort {
            get {
                return ResourceManager.GetString("MeasurementAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much noise.
        /// </summary>
        public static string Noisy {
            get {
                return ResourceManager.GetString("Noisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OhmField_green {
            get {
                object obj = ResourceManager.GetObject("OhmField_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OhmField_red {
            get {
                object obj = ResourceManager.GetObject("OhmField_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OhmField_yellow {
            get {
                object obj = ResourceManager.GetObject("OhmField_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Response.
        /// </summary>
        public static string PassResultText {
            get {
                return ResourceManager.GetString("PassResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PATH_TestDiagnostic {
            get {
                object obj = ResourceManager.GetObject("PATH_TestDiagnostic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PATH_TestIncomplete {
            get {
                object obj = ResourceManager.GetObject("PATH_TestIncomplete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PATH_TestIncompleteLarge {
            get {
                object obj = ResourceManager.GetObject("PATH_TestIncompleteLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PATH_TestPass {
            get {
                object obj = ResourceManager.GetObject("PATH_TestPass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PATH_TestPassLarge {
            get {
                object obj = ResourceManager.GetObject("PATH_TestPassLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PATH_TestRefer {
            get {
                object obj = ResourceManager.GetObject("PATH_TestRefer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PATH_TestReferLarge {
            get {
                object obj = ResourceManager.GetObject("PATH_TestReferLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diag.
        /// </summary>
        public static string PathMedical__AudiologyTest__AudiologyTestResult__Diagnostic {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__AudiologyTestResult__Diagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        public static string PathMedical__AudiologyTest__AudiologyTestResult__Incomplete {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__AudiologyTestResult__Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        public static string PathMedical__AudiologyTest__AudiologyTestResult__Pass {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__AudiologyTestResult__Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCR.
        /// </summary>
        public static string PathMedical__AudiologyTest__AudiologyTestResult__Refer {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__AudiologyTestResult__Refer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__Abort {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration abort.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationAbort {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration error.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationError {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration leaky.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationLeaky {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationLeaky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration noisy.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationNoisy {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationNoisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Timeout.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationTimeout {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__CalibrationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrode loose.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__ElectrodeLoose {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__ElectrodeLoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__Pass {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Error.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__ProbeError {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__ProbeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referred.
        /// </summary>
        public static string PathMedical__AudiologyTest__T1077AudiologyTestResult__Referred {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__T1077AudiologyTestResult__Referred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestObject__LeftEar {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestObject__LeftEar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestObject__RightEar {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestObject__RightEar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABR.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestType__ABR {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestType__ABR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABR.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestType__AbrScreening {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestType__AbrScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiogram.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestType__Audiogram {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestType__Audiogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPOAE.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestType__DPOAE {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestType__DPOAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP Diag.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestType__DpoaeDiagnostic {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestType__DpoaeDiagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestType__DpoaeScreening {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestType__DpoaeScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEOAE.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestType__TEOAE {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestType__TEOAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE.
        /// </summary>
        public static string PathMedical__AudiologyTest__TestType__TeoaeScreening {
            get {
                return ResourceManager.GetString("PathMedical__AudiologyTest__TestType__TeoaeScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PeakCounter {
            get {
                object obj = ResourceManager.GetObject("PeakCounter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe error. Try cleaning or replacing the probe tip..
        /// </summary>
        public static string ProbeError {
            get {
                return ResourceManager.GetString("ProbeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Clear Response.
        /// </summary>
        public static string ReferredResultText {
            get {
                return ResourceManager.GetString("ReferredResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Test_ClearResponse {
            get {
                object obj = ResourceManager.GetObject("Test_ClearResponse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Test_Incomplete {
            get {
                object obj = ResourceManager.GetObject("Test_Incomplete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Test_NoClearResponse {
            get {
                object obj = ResourceManager.GetObject("Test_NoClearResponse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TestDiagnostic {
            get {
                object obj = ResourceManager.GetObject("TestDiagnostic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string TestViewer_NoValueFound {
            get {
                return ResourceManager.GetString("TestViewer_NoValueFound", resourceCulture);
            }
        }
    }
}
